apiVersion: apps/v1
kind: Deployment
metadata:
  name: trade-signal-api
  labels:
    app: trade-signal-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: trade-signal-api
  template:
    metadata:
      labels:
        app: trade-signal-api
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8000"
        prometheus.io/path: "/metrics"
    spec:
      containers:
        - name: trade-signal-api
          image: thejas-sre/trade-signal-api:latest
          ports:
            - containerPort: 8000
          env:
            - name: REDIS_HOST
              value: "redis-service"
            - name: REDIS_POOL_SIZE
              value: "20"
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 30
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 3
